import 'package:get/get.dart';
import 'package:sellify/controller/accdelete_controller.dart';
import 'package:sellify/controller/addfav_controller.dart';
import 'package:sellify/controller/carbrandlist_controller.dart';
import 'package:sellify/controller/carvariation_controller.dart';
import 'package:sellify/controller/catgorylist_controller.dart';
import 'package:sellify/controller/editprofilecontroller.dart';
import 'package:sellify/controller/filter_controller/bikefilter_controller.dart';
import 'package:sellify/controller/filter_controller/carfilter_controller.dart';
import 'package:sellify/controller/filter_controller/commercialfilter_controller.dart';
import 'package:sellify/controller/filter_controller/commonfilter_controller.dart';
import 'package:sellify/controller/filter_controller/filters_controller.dart';
import 'package:sellify/controller/filter_controller/jobfilter_controller.dart';
import 'package:sellify/controller/filter_controller/mobilefilter_controller.dart';
import 'package:sellify/controller/filter_controller/propertyfilter_controller.dart';
import 'package:sellify/controller/filter_update.dart';
import 'package:sellify/controller/homedata_controller.dart';
import 'package:sellify/controller/inboxcontroller.dart';
import 'package:sellify/controller/listpackage_controller.dart';
import 'package:sellify/controller/makefeature_controller.dart';
import 'package:sellify/controller/mapsugestion.dart';
import 'package:sellify/controller/marksold_controller.dart';
import 'package:sellify/controller/msg_otp_controller.dart';
import 'package:sellify/controller/myadlist_controller.dart';
import 'package:sellify/controller/myfav_controller.dart';
import 'package:sellify/controller/pagelist_controller.dart';
import 'package:sellify/controller/paymentgaeway_cont.dart';
import 'package:sellify/controller/paystackcontroller.dart';
import 'package:sellify/controller/postad/bikecvehiclecontoller.dart';
import 'package:sellify/controller/postad/postbike_controller.dart';
import 'package:sellify/controller/postad/postcvehicle_controller.dart';
import 'package:sellify/controller/postad/commonpost_controller.dart';
import 'package:sellify/controller/postad/postmobile_controller.dart';
import 'package:sellify/controller/postad/properties_cont.dart';
import 'package:sellify/controller/postad_controller.dart';
import 'package:sellify/controller/postview_controller.dart';
import 'package:sellify/controller/profilewisepost_controller.dart';
import 'package:sellify/controller/refer_controller.dart';
import 'package:sellify/controller/repub_controller.dart';
import 'package:sellify/controller/topupwallet_controller.dart';
import 'package:sellify/controller/walletreport_controller.dart';

import '../controller/catwisepost_controller.dart';
import '../controller/searpost_controller.dart';

init() async {
  Get.lazyPut(() => CategoryListController());
  Get.lazyPut(() => CarbrandlistController());
  Get.lazyPut(() => PostadController());
  Get.lazyPut(() => PropertiesController());
  Get.lazyPut(() => PostmobileController());
  Get.lazyPut(() => PostbikeController());
  Get.lazyPut(() => BikescooterCvehicleContoller());
  Get.lazyPut(() => CommonPostController());
  Get.lazyPut(() => PostcvehicleController());
  Get.lazyPut(() => ListpackageController());
  Get.lazyPut(() => MapSuggestGetApiController());
  Get.lazyPut(() => MyadlistController());
  Get.lazyPut(() => HomedataController());
  Get.lazyPut(() => PaymentgaewayController());
  Get.lazyPut(() => CarvariationController());
  Get.lazyPut(() => AddfavController());
  Get.lazyPut(() => MyfavController());
  Get.lazyPut(() => SearchpostController());
  Get.lazyPut(() => CatwisePostController());
  Get.lazyPut(() => ProfilewiseController());
  Get.lazyPut(() => InboxController());
  Get.lazyPut(() => FilterupdateController());
  Get.lazyPut(() => CarfilterController());
  Get.lazyPut(() => PropertyFilController());
  Get.lazyPut(() => MobilefilterController());
  Get.lazyPut(() => JobfilterController());
  Get.lazyPut(() => BikefilterController());
  Get.lazyPut(() => CommonfilterController());
  Get.lazyPut(() => CommerfilterController());
  Get.lazyPut(() => FiltersController());
  Get.lazyPut(() => MarkSoldController());
  Get.lazyPut(() => PageListController());
  Get.lazyPut(() => ReferController());
  Get.lazyPut(() => ProfileEditController());
  Get.lazyPut(() => WalletreportController());
  Get.lazyPut(() => TopupWalletController());
  Get.lazyPut(() => PaystackController());
  Get.lazyPut(() => PostviewController());
  Get.lazyPut(() => AccDeletController());
  Get.lazyPut(() => RepubController());
  Get.lazyPut(() => MakeFeatureController());
  Get.lazyPut(() => MsgOtpController());
}